import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ApolloWrapper } from './lib/apollo-wrapper'

// COMPONENTS
import Navbar from './components/navigation/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} max-w-screen-2xl mx-auto  border-2 border-red-400`}
      >
        <ApolloWrapper>
          <Navbar />

          {children}
        </ApolloWrapper>
      </body>
    </html>
  )
}
